name: "jupytext-action"
author: zcysxy
description: "Convert between Jupyter notebooks and text formats using jupytext"

inputs:
  github_token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}

  input_format:
    description: "Input format (e.g., md, py, ipynb)"
    required: false
    default: "md"

  output_format:
    description: "Output format (e.g., ipynb, py, md)"
    required: false
    default: "ipynb"

  input_directory:
    description: "Directory containing input files to convert"
    required: false
    default: "./"

  output_dir:
    description: "Output directory for converted files"
    required: false
    default: "./jupyter/"

  check:
    description: "Which files to check: 'all', 'latest', or 'frontmatter'"
    required: false
    default: "frontmatter"

  frontmatter_field:
    description: "Frontmatter field name to check when using frontmatter check mode"
    required: false
    default: "notebook"

  frontmatter_value:
    description: "Value in frontmatter field that indicates conversion (for check=frontmatter)"
    required: false
    default: "true"

  disable_git_commit:
    description: "Disable Git commit after conversion (useful for GitHub releases)"
    required: false
    default: "false"

  comment_magics:
    description: "Whether to comment magic commands"
    required: false
    default: "false"

  split_at_heading:
    description: "Whether to split at headings"
    required: false
    default: "false"

  sync_mode:
    description: "Sync mode: 'one-way' or 'two-way'"
    required: false
    default: "one-way"

  target_repository:
    description: "Target repository"
    required: false

  target_branch:
    description: "Target branch"
    required: false

  pull_request_repository:
    description: "Pull request repository"
    required: false

  pull_request_branch:
    description: "Pull request branch"
    required: false

  commit_message:
    description: "Commit message"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book"
  color: "blue"
