name: "Jupytext Action"
author: zcysxy
description: "Convert between Jupyter notebooks and text formats using jupytext"

inputs:
  github_token:
    description: "GitHub token"
    required: true

  input_format:
    description: "Input format (py, markdown, notebook, etc.)"
    required: true
    default: "md"

  output_format:
    description: "Output format (py, markdown, notebook, etc.)"
    required: true
    default: "ipynb"

  input_directory:
    description: "Directory containing input files to convert"
    required: false
    default: "./"

  output_dir:
    description: "Directory to store output files"
    required: false
    default: "./jupyter/"

  check:
    description: "Mode to check files (all, latest, frontmatter)"
    required: false
    default: "frontmatter"

  frontmatter_field:
    description: "Field in frontmatter to check (for check=frontmatter)"
    required: false
    default: "notebook"

  comment_magics:
    description: "Comment out Jupyter magic commands"
    required: false
    default: "false"

  split_at_heading:
    description: "Split markdown at heading"
    required: false
    default: "false"

  sync_mode:
    description: "Sync mode (one-way, two-way)"
    required: false
    default: "one-way"

  commit_message:
    description: "Commit message for the auto-generated commit"
    required: false
    default: "Convert files using jupytext"

  target_repository:
    description: "Target repository to push to"
    required: false

  target_branch:
    description: "Target branch to push to"
    required: false

  pull_request_repository:
    description: "Pull request repository"
    required: false

  pull_request_branch:
    description: "Pull request branch"
    required: false

  disable_git_commit:
    description: "Disable git commit (only convert files)"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "book"
  color: "blue"
