name: test-markdown
on: [push]

jobs:
  build:
    name: jupytext-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Jupytext Action 
        uses: zcysxy/jupytext-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input_directory: "test-notebooks"
          input_format: md
          output_format: ipynb
          disable_git_commit: false
          frontmatter_field: type
          frontmatter_value: jupyter
